version: "3.7"

services:
  sync-to-airtable:
    image: pozylon/allmengang-kwh
    env_file: .env
    deploy:
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 0 0 * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none